using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using GPPSA.Application.Dtos.Employee;
using GPPSA.Domain;

namespace GPPSA.Application.Mappings
{
    public class EmployeeProfile:Profile
    {
        public EmployeeProfile()
        {
            // Configure mapping from CreateEmployeeDtos to Employee
            CreateMap<CreateEmployeeDtos ,Employee>()
            .ForMember(dest => dest.Id, opt => opt.Ignore()) // Ignore ID as it will be generated by the database
            .ForMember(dest => dest.Department, opt => opt.Ignore()); // Ignore Department navigation property
        
            CreateMap<Employee, EmployeeResponseDto>()
            .ForMember(
                dest => dest.DepartmentName,
                // Safely handle possible null Department to avoid dereference of a null reference
                opt => opt.MapFrom(src => src.Department == null ? null : src.Department.DepartmentName)
            );
            CreateMap<UpdateEmployeeDto, Employee>();
        }
    }
}