name: Deploy GPPSA UI to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'Frontend/**' # Only triggers when files change in the Frontend folder
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'

    - name: Install dependencies
      run: |
        cd Frontend/GPPSA\ Ui
        npm install

    - name: Build
      run: |
        cd Frontend/GPPSA\ Ui
        npm run build
      

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'gppsa-ui'
        publish-profile: ${{ secrets.AZURE_FRONTEND_PUBLISH_PROFILE }}
        package: Frontend/GPPSA\ Ui/dist/gppsa-ui/browser # Paths vary by Angular version. Check your dist folder output name.
