name: Deploy Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      - 'Backend/**'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore, Build and Publish
      run: |
        cd Backend
        dotnet restore
        dotnet build --configuration Release --no-restore
        dotnet publish --configuration Release --no-build -o ../publish

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v3
      with:
        app-name: 'gppsa-api'
        publish-profile: ${{ secrets.AZURE_BACKEND_PUBLISH_PROFILE }}
        package: './publish'